Adds docstrings, hides DtmiConventions.
Azure/iot-plugandplay-models-tools pull request #131
Opened 2020-11-17 02:55 UTC by digimaun

- Adds docstrings to all public `ResolverClient` methods.
- Makes DtmiConventions `internal` with an explicit exception/friend for `dmr-client` as `dmr-client` is always coupled with the `ResolverClient`.
- `IsValidDtmi` is no longer static for streamlined usage of `ResolverClient`.
- Increments dmr-client to `1.0.0.0-beta`.
  - `ResolverClient` is also incremented but still on major version 0 until some loose ends are tied up.

2020-11-17 16:15 UTC, montgomp requested changes

2020-11-17 16:15 UTC, montgomp commented on clients/dotnet/Azure.Iot.ModelsRepository/DtmiConventions.cs
> +    internal class DtmiConventions
I'm not sure I see the benefit of making this class internal just to expose it to specific assemblies in AssemblyInfo. Why 
not keep it public so that we can use it as the single source of how to validate DTMI for .Net projects?

2020-11-17 16:16 UTC, montgomp commented on clients/dotnet/Azure.Iot.ModelsRepository/Azure.Iot.ModelsRepository.csproj
> +    <Version>0.0.14</Version>
Should this assembly be going beta as well?

2020-11-17 17:21 UTC, digimaun commented on clients/dotnet/Azure.Iot.ModelsRepository/Azure.Iot.ModelsRepository.csproj
> +    <Version>0.0.14</Version>
The beta increment for the SDK should be when it covers all the elements of track 2 (it is close). The SDK can iterate independently of dmr-client.

2020-11-17 17:36 UTC, digimaun commented on clients/dotnet/Azure.Iot.ModelsRepository/DtmiConventions.cs
> +    internal class DtmiConventions
The reasoning behind this move is to have a single public interface/entrypoint into the SDK and that is via the ResolverClient.

What does DtmiConventions provide?
- Is a string value a DTMI?
  - This is *already* exposed via ResolverClient.IsValidDtmi() .
- Given this dtmi give me a path (fully qualified or not)
  - By using the SDK, DTMI paths are an abstracted detail. This change makes the assumption that forming "dtmi paths" (outside of ResolveAsync) are negligible use case for the end user with the exception of `dmr-client` for the following...

The reason its explicitly exposed to `dmr-client` is that `dmr-client` is **always** coupled with the SDK and the dmr-client has functionality to import a model file, and the DtmiConventions fully qualified path is convenient to use.

2020-11-17 21:04 UTC, montgomp approved these changes

2020-11-18 18:36 UTC, montgomp approved these changes

2020-11-18 18:37 UTC, merged